"""Governed adaptive tuning surface for AM Workbench."""

from __future__ import annotations

from vetinari.workbench.adaptive_tuning.adapters import (
    canonical_dependency_type_names,
    hypothesis_to_hardware_advisory,
    hypothesis_to_network_advisory,
    hypothesis_to_preference_card_draft,
    proposal_to_approval_request,
    proposal_to_artifact_review,
    proposal_to_improvement_candidate,
    proposal_to_shadow_rollback,
)
from vetinari.workbench.adaptive_tuning.config import AdaptiveTuningConfig, load_adaptive_tuning_config
from vetinari.workbench.adaptive_tuning.contracts import (
    AdaptationTarget,
    AdaptiveHypothesis,
    AdaptiveTuningError,
    AdaptiveTuningPolicyDecision,
    ControlAction,
    EvidenceBlocker,
    EvidenceScope,
    EvidenceStatus,
    FrictionObservation,
    FrictionSignalKind,
    HypothesisStatus,
    LocalChangeProposal,
    NormalizedEvidence,
    PreviewPacket,
    PromotionEvidence,
    ProposalState,
    RiskTier,
    RollbackRequirement,
    UserControlDecision,
)
from vetinari.workbench.adaptive_tuning.engine import AdaptiveTuningEngine
from vetinari.workbench.adaptive_tuning.policy import (
    AdaptiveTuningPolicy,
    classify_target_risk,
    evaluate_proposal_policy,
    observation_blockers,
    silent_observation_target_allowed,
)
from vetinari.workbench.adaptive_tuning.signals import (
    normalize_any_signal,
    normalize_hardware_proposal,
    normalize_network_decision,
    normalize_observation,
    normalize_preference_card,
    normalize_user_input_signal,
)
from vetinari.workbench.adaptive_tuning.store import (
    DEFAULT_ADAPTIVE_TUNING_STATE_ROOT,
    AdaptiveTuningSnapshot,
    AdaptiveTuningStore,
)

__all__ = [
    "DEFAULT_ADAPTIVE_TUNING_STATE_ROOT",
    "AdaptationTarget",
    "AdaptiveHypothesis",
    "AdaptiveTuningConfig",
    "AdaptiveTuningEngine",
    "AdaptiveTuningError",
    "AdaptiveTuningPolicy",
    "AdaptiveTuningPolicyDecision",
    "AdaptiveTuningSnapshot",
    "AdaptiveTuningStore",
    "ControlAction",
    "EvidenceBlocker",
    "EvidenceScope",
    "EvidenceStatus",
    "FrictionObservation",
    "FrictionSignalKind",
    "HypothesisStatus",
    "LocalChangeProposal",
    "NormalizedEvidence",
    "PreviewPacket",
    "PromotionEvidence",
    "ProposalState",
    "RiskTier",
    "RollbackRequirement",
    "UserControlDecision",
    "canonical_dependency_type_names",
    "classify_target_risk",
    "evaluate_proposal_policy",
    "hypothesis_to_hardware_advisory",
    "hypothesis_to_network_advisory",
    "hypothesis_to_preference_card_draft",
    "load_adaptive_tuning_config",
    "normalize_any_signal",
    "normalize_hardware_proposal",
    "normalize_network_decision",
    "normalize_observation",
    "normalize_preference_card",
    "normalize_user_input_signal",
    "observation_blockers",
    "proposal_to_approval_request",
    "proposal_to_artifact_review",
    "proposal_to_improvement_candidate",
    "proposal_to_shadow_rollback",
    "silent_observation_target_allowed",
]
