"""Keyword feature tables for deterministic ML classifiers."""

from __future__ import annotations

from vetinari.types import GoalCategory

# Goal categories aligned to GoalCategory enum (M4 ontology unification)
GOAL_CATEGORIES = [cat.value for cat in GoalCategory]

# Keyword maps for goal classification — keys are GoalCategory values
_GOAL_KEYWORDS: dict[str, list[str]] = {
    GoalCategory.CODE.value: [
        "implement",
        "create",
        "build",
        "write",
        "add",
        "function",
        "class",
        "module",
        "api",
        "endpoint",
        "feature",
        "code",
        "program",
        "develop",
        "fix",
        "bug",
        "debug",
        "error",
        "refactor",
        "test",
        "unittest",
        "pytest",
    ],
    GoalCategory.RESEARCH.value: [
        "research",
        "investigate",
        "find",
        "search",
        "explore",
        "evaluate",
        "compare",
        "analyze",
        "study",
        "learn about",
        "what is",
        "how does",
    ],
    GoalCategory.DOCS.value: [
        "document",
        "readme",
        "docstring",
        "comment",
        "explain",
        "describe",
        "markdown",
        "changelog",
        "wiki",
        "manual",
        "api docs",
    ],
    GoalCategory.CREATIVE.value: [
        "write story",
        "narrative",
        "fiction",
        "campaign",
        "creative",
        "blog post",
        "article",
    ],
    GoalCategory.SECURITY.value: [
        "security",
        "audit",
        "vulnerability",
        "pentest",
        "review security",
        "threat",
        "owasp",
        "cve",
    ],
    GoalCategory.DATA.value: [
        "database",
        "schema",
        "migration",
        "etl",
        "sql",
        "data",
        "query",
        "table",
    ],
    GoalCategory.DEVOPS.value: [
        "deploy",
        "release",
        "publish",
        "docker",
        "ci/cd",
        "pipeline",
        "kubernetes",
        "infrastructure",
    ],
    GoalCategory.UI.value: [
        "ui",
        "ux",
        "frontend",
        "design",
        "wireframe",
        "layout",
        "css",
        "component",
    ],
    GoalCategory.IMAGE.value: [
        "logo",
        "icon",
        "mockup",
        "diagram",
        "image",
        "generate image",
        "illustration",
    ],
}


# Map to existing DefectCategory values
DEFECT_CATEGORIES = [
    "hallucinated_import",
    "ambiguous_spec",
    "model_limitation",
    "insufficient_context",
    "integration_error",
    "logic_error",
    "style_violation",
]

_DEFECT_KEYWORDS: dict[str, list[str]] = {
    "hallucinated_import": [
        "import",
        "module not found",
        "no module named",
        "cannot import",
        "importerror",
        "modulenotfounderror",
        "undefined name",
    ],
    "ambiguous_spec": [
        "unclear",
        "ambiguous",
        "not specified",
        "missing requirement",
        "vague",
        "underspecified",
        "what do you mean",
    ],
    "model_limitation": [
        "too complex",
        "context length",
        "token limit",
        "cannot handle",
        "out of scope",
        "beyond capability",
        "model struggled",
    ],
    "insufficient_context": [
        "missing context",
        "need more information",
        "file not found",
        "reference not available",
        "unknown variable",
        "undeclared",
    ],
    "integration_error": [
        "integration",
        "compatibility",
        "api mismatch",
        "version conflict",
        "interface",
        "contract",
        "type error",
        "signature",
    ],
    "logic_error": [
        "logic error",
        "incorrect output",
        "wrong result",
        "off by one",
        "infinite loop",
        "race condition",
        "deadlock",
        "incorrect behavior",
    ],
    "style_violation": [
        "style",
        "formatting",
        "naming",
        "convention",
        "lint",
        "ruff",
        "pep8",
        "docstring",
        "type hint",
    ],
}
